import { PrismaClient, Prisma, Difficulty } from "@prisma/client";

// ─── Seeded PRNG (mulberry32) ────────────────────────────────────────────────
// Deterministic — same seed always produces the same shuffle. Used so a paper
// can be regenerated byte-identical from the stored seed.

export function makeRng(seed: number): () => number {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function hashSeed(input: string): number {
  // Simple 32-bit FNV-1a for text → integer seed
  let h = 0x811C9DC5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

export function shuffleWithRng<T>(arr: T[], rng: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ─── Types ────────────────────────────────────────────────────────────────────

export type SectionType = "MCQ" | "SUBJECTIVE";
export type SubjectiveSubType = "FILL_BLANK" | "ONE_WORD" | "SHORT_ANSWER" | "LONG_ANSWER";

export interface DifficultyDist {
  easy?: number;    // 0..1 (fractions) OR 0..100 (percent) — normalised internally
  medium?: number;
  hard?: number;
}

export interface SectionSpec {
  title?: string;
  type: SectionType;
  // When type=SUBJECTIVE, subType narrows the pool (fill-in-blanks only,
  // one-word only, etc). NULL means "any subjective". Ignored for MCQ.
  subType?: SubjectiveSubType;
  marksPerQuestion: number;
  numQuestions: number;
  // "Attempt any N of the following M" pattern — samples M questions but
  // shows an instruction line telling students they only need to attempt N.
  // NULL means all N are compulsory.
  attemptAny?: number;
  // Per-section instruction line, shown above the questions.
  instructions?: string;
  blankLines?: number;
  // Scope — pool of questions to sample from. Only one shape is used at a
  // time; more specific wins (chapters > subSubject > subjects > class).
  //   classId       — whole class (all subjects, all chapters, all questions)
  //   subSubjectId  — one sub-subject (all its chapters)
  //   subjectIds    — one or more subjects (all their chapters, direct + via sub-subjects)
  //   chapterIds    — one or more specific chapters
  scope: {
    classId?: string;
    subSubjectId?: string;
    subjectIds?: string[];
    chapterIds?: string[];
  };
  shuffle?: boolean;
  distributeAcrossChapters?: boolean;   // when true and scope has multiple chapters, balance N across them
  difficulty?: DifficultyDist;          // optional target distribution
}

export interface SampledSection {
  spec: SectionSpec;
  questions: any[];                     // full question rows (with subject/chapter includes)
}

export interface SampleResult {
  sections: SampledSection[];
  errors: string[];
}

// ─── Helper: bucket questions by chapter ─────────────────────────────────────

function groupByChapter<T extends { chapterId: string | null }>(qs: T[]): Map<string, T[]> {
  const m = new Map<string, T[]>();
  for (const q of qs) {
    const k = q.chapterId ?? "__no_chapter__";
    const arr = m.get(k);
    if (arr) arr.push(q); else m.set(k, [q]);
  }
  return m;
}

// Given target counts per bucket totalling N, distribute picks fairly.
// e.g. 5 chapters × need 20 = 4 each. If a chapter has only 3, redistribute.
function planPerChapter(
  buckets: Map<string, any[]>,
  wanted: number
): Map<string, number> {
  const plan = new Map<string, number>();
  const keys = [...buckets.keys()];
  if (keys.length === 0) return plan;

  const base = Math.floor(wanted / keys.length);
  let remainder = wanted - base * keys.length;

  // First pass: base allocation, capped by availability
  const capped: string[] = [];
  const flex: string[] = [];
  for (const k of keys) {
    const avail = buckets.get(k)!.length;
    const take = Math.min(base, avail);
    plan.set(k, take);
    if (take < base) capped.push(k); else flex.push(k);
  }

  // Give remainder to flex buckets one-by-one
  let ci = 0;
  while (remainder > 0 && flex.length > 0) {
    const k = flex[ci % flex.length];
    if (plan.get(k)! < buckets.get(k)!.length) {
      plan.set(k, plan.get(k)! + 1);
      remainder--;
    } else {
      // this bucket is full — remove from flex
      flex.splice(flex.indexOf(k), 1);
      if (flex.length === 0) break;
      continue;
    }
    ci++;
  }

  // Any shortfall from capped buckets → redistribute to flex
  const shortfall = wanted - [...plan.values()].reduce((a, b) => a + b, 0);
  if (shortfall > 0) {
    const remaining = keys
      .map((k) => ({ k, avail: buckets.get(k)!.length - plan.get(k)! }))
      .filter((x) => x.avail > 0)
      .sort((a, b) => b.avail - a.avail);
    let need = shortfall;
    for (const { k } of remaining) {
      while (need > 0 && plan.get(k)! < buckets.get(k)!.length) {
        plan.set(k, plan.get(k)! + 1);
        need--;
      }
      if (need === 0) break;
    }
  }

  return plan;
}

// Plan per-difficulty counts summing to `wanted`
function planDifficulty(dist: DifficultyDist | undefined, wanted: number): { easy: number; medium: number; hard: number } | null {
  if (!dist) return null;
  const parts = {
    easy: Math.max(0, dist.easy ?? 0),
    medium: Math.max(0, dist.medium ?? 0),
    hard: Math.max(0, dist.hard ?? 0),
  };
  const sum = parts.easy + parts.medium + parts.hard;
  if (sum <= 0) return null;
  // Normalise to fractions, then take round(n * fraction), fix any rounding drift
  const fEasy = parts.easy / sum;
  const fMed = parts.medium / sum;
  let easy = Math.round(fEasy * wanted);
  let medium = Math.round(fMed * wanted);
  let hard = wanted - easy - medium;
  // If any bucket went negative from rounding, push it into medium (safest default)
  if (hard < 0) { medium += hard; hard = 0; }
  if (medium < 0) { easy += medium; medium = 0; }
  if (easy < 0) easy = 0;
  return { easy, medium, hard };
}

// ─── Availability report ─────────────────────────────────────────────────────

export interface AvailabilityBreakdown {
  total: number;
  byDifficulty: { easy: number; medium: number; hard: number };
  byChapter: Array<{ chapterId: string; chapterName?: string; count: number }>;
}

// ─── The core sampler ────────────────────────────────────────────────────────

export interface SampleOptions {
  seed?: number;                // if omitted, non-deterministic
  excludeIds?: Set<string>;     // ids already picked in a prior section — never reuse
}

export async function sampleSection(
  prisma: PrismaClient,
  spec: SectionSpec,
  opts: SampleOptions = {}
): Promise<{ questions: any[]; error?: string; breakdown?: AvailabilityBreakdown }> {
  const rng = makeRng(opts.seed ?? Math.floor(Math.random() * 0xFFFFFFFF));
  const label = spec.title || `Section`;

  const hasChapters = (spec.scope?.chapterIds?.length ?? 0) > 0;
  const hasSubSubject = !!spec.scope?.subSubjectId;
  const hasSubjects = (spec.scope?.subjectIds?.length ?? 0) > 0;
  const hasClass = !!spec.scope?.classId;
  if (!hasChapters && !hasSubSubject && !hasSubjects && !hasClass) {
    return { questions: [], error: `${label}: scope must include classId, subSubjectId, subjectIds, or chapterIds` };
  }

  const where: Prisma.QuestionWhereInput = { isActive: true, type: spec.type };
  // Narrow to the specific subjective sub-type if requested (fill-in-blanks
  // only, etc). Only meaningful when type=SUBJECTIVE; harmless otherwise.
  if (spec.type === "SUBJECTIVE" && spec.subType) {
    where.subType = spec.subType as any;
  }
  // Most-specific scope wins. All four shapes filter down to the same
  // final pool of questions, just through different join paths.
  if (hasChapters) {
    where.chapterId = { in: spec.scope.chapterIds! };
  } else if (hasSubSubject) {
    // All chapters that live under this sub-subject.
    where.chapter = { subSubjectId: spec.scope.subSubjectId };
  } else if (hasSubjects) {
    where.subjectId = { in: spec.scope.subjectIds! };
  } else if (hasClass) {
    // All subjects that belong to this class → questions of those subjects.
    where.subject = { classId: spec.scope.classId };
  }
  if (opts.excludeIds && opts.excludeIds.size > 0) where.id = { notIn: [...opts.excludeIds] };

  const candidates = await prisma.question.findMany({
    where,
    include: {
      subject: { select: { id: true, name: true } },
      chapter: {
        select: {
          id: true, name: true,
          subSubject: { select: { id: true, name: true } },
        },
      },
    },
  });

  // Build availability breakdown up front — used both for planning and error reporting
  const byChapterMap = groupByChapter(candidates);
  const breakdown: AvailabilityBreakdown = {
    total: candidates.length,
    byDifficulty: {
      easy: candidates.filter((q) => q.difficulty === "EASY").length,
      medium: candidates.filter((q) => q.difficulty === "MEDIUM").length,
      hard: candidates.filter((q) => q.difficulty === "HARD").length,
    },
    byChapter: [...byChapterMap.entries()].map(([cid, arr]) => ({
      chapterId: cid,
      chapterName: arr[0]?.chapter?.name,
      count: arr.length,
    })),
  };

  if (candidates.length < spec.numQuestions) {
    const chapterList = breakdown.byChapter
      .map((c) => `${c.chapterName ?? "(no chapter)"}: ${c.count}`)
      .join(", ");
    return {
      questions: [],
      breakdown,
      error: `${label}: need ${spec.numQuestions} ${spec.type} question(s) but only ${candidates.length} available. Per-chapter: ${chapterList}`,
    };
  }

  // Optional: difficulty distribution
  const diffPlan = planDifficulty(spec.difficulty, spec.numQuestions);
  let byDiffPools: Record<Difficulty, any[]> | null = null;
  if (diffPlan) {
    byDiffPools = {
      EASY: candidates.filter((q) => q.difficulty === "EASY"),
      MEDIUM: candidates.filter((q) => q.difficulty === "MEDIUM"),
      HARD: candidates.filter((q) => q.difficulty === "HARD"),
    };
    // Validate feasibility with graceful borrowing: if a level is short, borrow from adjacent
    const need = { EASY: diffPlan.easy, MEDIUM: diffPlan.medium, HARD: diffPlan.hard };
    // Borrow chain: EASY↔MEDIUM↔HARD
    const borrow = (from: Difficulty, to: Difficulty) => {
      const short = need[to] - byDiffPools![to].length;
      if (short <= 0) return;
      const spare = byDiffPools![from].length - need[from];
      const move = Math.min(short, Math.max(0, spare));
      need[from] += move;
      need[to] -= move;
    };
    borrow("MEDIUM", "EASY"); borrow("HARD", "MEDIUM"); borrow("EASY", "MEDIUM");
    borrow("MEDIUM", "HARD"); borrow("EASY", "HARD"); borrow("HARD", "EASY");
    const shortfall =
      Math.max(0, need.EASY - byDiffPools.EASY.length) +
      Math.max(0, need.MEDIUM - byDiffPools.MEDIUM.length) +
      Math.max(0, need.HARD - byDiffPools.HARD.length);
    if (shortfall > 0) {
      return {
        questions: [],
        breakdown,
        error: `${label}: requested difficulty mix (E:${diffPlan.easy} M:${diffPlan.medium} H:${diffPlan.hard}) cannot be met from available pool (E:${breakdown.byDifficulty.easy} M:${breakdown.byDifficulty.medium} H:${breakdown.byDifficulty.hard}). Adjust the mix or upload more questions.`,
      };
    }
    diffPlan.easy = need.EASY; diffPlan.medium = need.MEDIUM; diffPlan.hard = need.HARD;
  }

  // Pick from pool(s)
  let picked: any[] = [];

  const pickWithChapterFairness = (pool: any[], n: number): any[] => {
    if (n <= 0 || pool.length === 0) return [];
    const buckets = groupByChapter(pool);
    const plan = planPerChapter(buckets, n);
    const out: any[] = [];
    for (const [cid, count] of plan) {
      const bucket = buckets.get(cid)!;
      const shuffled = shuffleWithRng(bucket, rng);
      out.push(...shuffled.slice(0, count));
    }
    return out;
  };

  const pickRandom = (pool: any[], n: number): any[] => shuffleWithRng(pool, rng).slice(0, n);

  if (diffPlan && byDiffPools) {
    // Sample each difficulty separately, applying chapter fairness within it if requested
    for (const [level, take] of [["EASY", diffPlan.easy], ["MEDIUM", diffPlan.medium], ["HARD", diffPlan.hard]] as const) {
      const pool = byDiffPools[level];
      const chunk = spec.distributeAcrossChapters
        ? pickWithChapterFairness(pool, take)
        : pickRandom(pool, take);
      picked.push(...chunk);
    }
  } else if (spec.distributeAcrossChapters) {
    picked = pickWithChapterFairness(candidates, spec.numQuestions);
  } else {
    picked = pickRandom(candidates, spec.numQuestions);
  }

  // Final ordering: shuffle unless explicitly disabled
  const ordered = spec.shuffle === false ? picked : shuffleWithRng(picked, rng);
  return { questions: ordered, breakdown };
}

/**
 * Sample all sections in order, respecting the "no repeats across sections" invariant.
 * A single top-level seed drives every section (each section reuses the same seed but seeded
 * by section index to keep sections independent yet reproducible).
 */
export async function sampleComposition(
  prisma: PrismaClient,
  specs: SectionSpec[],
  topLevelSeed?: number
): Promise<SampleResult> {
  const seedBase = topLevelSeed ?? Math.floor(Math.random() * 0xFFFFFFFF);
  const excluded = new Set<string>();
  const sections: SampledSection[] = [];
  const errors: string[] = [];

  for (let i = 0; i < specs.length; i++) {
    const spec = specs[i];
    const r = await sampleSection(prisma, spec, {
      seed: seedBase + i * 1013904223,   // LCG-style stride per section
      excludeIds: excluded,
    });
    if (r.error) {
      errors.push(r.error);
      continue;
    }
    for (const q of r.questions) excluded.add(q.id);
    sections.push({ spec, questions: r.questions });
  }
  return { sections, errors };
}
